image:
  tag: v0.1.3

replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

services:
  frontend:
    type: NodePort
    port: 80
    targetPort: 8080
    nodePort: 30001

ingress:
  host: shop.35.228.29.20.nip.io